name: twitch_clone
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  firebase_auth: ^3.9.0
  firebase_core: ^1.22.0
  cloud_firestore: ^3.4.8
  flutter_screenutil: ^5.5.4
  image_picker: ^0.8.5+3
  firebase_storage: ^10.3.9
  agora_rtc_engine: ^5.3.0
  permission_handler: ^10.0.1
  uuid: ^3.0.6
  http: ^0.13.5
  timeago: ^3.3.0
  file_picker: ^5.2.0+1
  flutter: 
    sdk: flutter
  dotted_border: ^2.0.0+2
   

dev_dependencies: 
  flutter_lints: ^2.0.0
  lints: 2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/

